### ISSUE TITLE
Where did you find these classes?

### ISSUE THREAD

**Issue by binarynoise** [fonix232/SCoverRE#1]
Which jar/apk/... did you reverse engineer?
I need the file to fix a Samsung app crashing.

**Comment by nav1s** [comment]
@binarynoise have you managed to find it? (ran into a similar issue with the samsung notes app)

**Comment by binarynoise** [comment]
@nav1s Most of them were in Samsung's framework.jar, the rest was in the Notes.apk itself. 
I still didn't get it to run (some strange ClassLoader issues)
